//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoaches.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int C_idChoisez { get; set; }
        public int C_idUtilisateur { get; set; }
        public Nullable<System.DateTime> DateDub { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public Nullable<int> Peroide { get; set; }
        public Nullable<bool> autoReview { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Choix Choix { get; set; }
    }
}
