//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoaches.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PFEEntities : DbContext
    {
        public PFEEntities()
            : base("name=PFEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carte> Cartes { get; set; }
        public virtual DbSet<Commentaire> Commentaires { get; set; }
        public virtual DbSet<Entraineur> Entraineurs { get; set; }
        public virtual DbSet<LinkCertification> LinkCertifications { get; set; }
        public virtual DbSet<LinkPost> LinkPosts { get; set; }
        public virtual DbSet<MessageEnv> MessageEnvs { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<Paiement> Paiements { get; set; }
        public virtual DbSet<Personne> Personnes { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Reponse> Reponses { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<WhatPeopleSay> WhatPeopleSays { get; set; }
        public virtual DbSet<reseauxSociaux> reseauxSociauxes { get; set; }
        public virtual DbSet<Abonnement> Abonnements { get; set; }
        public virtual DbSet<EnvoyePar> EnvoyePars { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<Choix> Choixes { get; set; }
        public virtual DbSet<AdminBackend> AdminBackends { get; set; }
    }
}
