//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoaches.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvoyePar
    {
        public int C_idEntraineur { get; set; }
        public int C_idUtilisateur { get; set; }
        public int C_idMessage { get; set; }
        public Nullable<bool> Deriction { get; set; }
    
        public virtual Entraineur Entraineur { get; set; }
        public virtual MessageEnv MessageEnv { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
