//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoaches.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reponse
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateRpnd { get; set; }
        public string TextRpnd { get; set; }
        public Nullable<int> C_idCommentaire { get; set; }
        public Nullable<int> C_idPesonne { get; set; }
    
        public virtual Commentaire Commentaire { get; set; }
        public virtual Personne Personne { get; set; }
    }
}
